import { COLUMNS_DIMENSION_PROPERTIES } from "@mui/x-data-grid/hooks/features/columns/gridColumnsUtils";

export const HeadingData = [
  {
    id: "sl_no",
    headerName:'Sl No',
    numeric: true,
    disablePadding: false,
    label: "sl_no",
    field: "sl_no",
    minWidth: 100,
  },
  {
    id: "business_code",
    headerName:'Business Code',
   
    numeric: true,
    disablePadding: false,
    label: "business_code",
    field: "business_code",
    minWidth: 100,
  },
  {
    id: "cust_number",
    headerName : 'Cust Number',
    numeric: true,
    disablePadding: true,
    label: "cust_number",
    field: "cust_number",
    minWidth: 100,
  },
  {
    id: "clear_date",
    headerName:'Clear date',
    numeric: false,
    disablePadding: true,
    label: "clear_date",
    field: "clear_date",
    minWidth: 100,
  },
  {
    id: "buisness_year",
    headerName:'Business Year',
    numeric: true,
    disablePadding: true,
    label: "buisness_year",
    field: "buisness_year",
    minWidth: 100,
  },
  {
    id: "doc_id",
    headerName:'Doc Id',
    numeric: true,
    disablePadding: true,
    label: "doc_id",
    field: "doc_id",
    minWidth: 100,
  },
  {
    id: "posting_date",
    headerName:'Posting Date',
    numeric: false,
    disablePadding: true,
    label: "posting_date",
    field: "posting_date",
    minWidth: 100,
  },
  {
    id: "document_create_date",
    headerName:'Document Create Date',
    numeric: false,
    disablePadding: true,
    label: "document_create_date",
    field: "document_create_date",
    minWidth: 100,
  },
  {
    id: "due_in_date",
    headerName:'Due Date',
    numeric: false,
    disablePadding: true,
    label: "due_in_date",
    field: "due_in_date",
    minWidth: 100,
  },
  {
    id: "invoice_currency",
    headerName:'Invoice Currency',
    numeric: false,
    disablePadding: true,
    label: "invoice_currency",
    field: "invoice_currency",
    minWidth: 100,
  },
  {
    id: "document_type",
    headerName:'Document Type',
    numeric: false,
    disablePadding: true,
    label: "document_type",
    field: "document_type",
    minWidth: 100,
  },
  {
    id: "posting_id",
    headerName:'Posting Id',
    numeric: false,
    disablePadding: true,
    label: "posting_id",
    field: "posting_id",
    minWidth: 100,
  },
  {
    id: "total_open_amount",
    headerName:'Total Open Amount',
    numeric: true,
    disablePadding: true,
    label: "total_open_amount",
    field: "total_open_amount",
    minWidth: 100,
  },
  {
    id: "baseline_create_date",
    headerName:'Baseline Create Date',
    numeric: false,
    disablePadding: true,
    label: "baseline_create_date",
    field: "baseline_create_date",
    minWidth: 100,
  },
  {
    id: "cust_payment_terms",
    headerName:'Cust Payment Terms',
    numeric: false,
    disablePadding: true,
    label: "cust_payment_terms",
    field: "cust_payment_terms",
    minWidth: 100,
  },
  {
    id: "invoice_id",
    headerName:'Invoice Id',
    numeric: true,
    disablePadding: true,
    label: "invoice_id",
    field: "invoice_id",
    minWidth: 100,
  },
  {
    id:'aging_bucket',
    headerName:'Aging Bucket',
    numeric: false,
    disablePadding: true,
    label: 'aging_bucket',
    field: 'aging_bucket',
    minWidth: 100,

}
];
